### ISSUE TITLE
Apple deprecated API -- Needs update to UnityAds SDK 3.3.0+

### ISSUE THREAD

**Issue by fedellen** [byrobingames/unityads#5]
Recently Apple has been sending an auto rejection email with the following message:

> ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

With help from the Stencyl Discord I was directed to the UnityAds release notes on SDK 3.3: https://github.com/Unity-Technologies/unity-ads-ios/releases

```
Added
OS 13 update:
Deprecated UI webview. Due to Apple's changes, Unity Ads no longer supports iOS 7 and 8.
```

It seems like an easy fix but I'm well above my league. I also noticed your donation button is no longer linked to a valid Paypal account. Thanks for reading and for the awesome extensions!

**Comment by byrobingames** [comment]
As far I can read from Unity site: 
If you manually download Framework 3.3.0 from here.
https://github.com/Unity-Technologies/unity-ads-ios/releases/tag/3.3.0 

1) Delete UnityAds.framework from folder:  ../STENCYLWORKS/engine-extensions/unityads/frameworks
2) Unzip UnityAds.framework.zip in folder ../STENCYLWORKS/engine-extensions/unityads/frameworks
3) run clean project.

This should work..(not tested but you can test it.)

Don't download framework 3.4.0, this version will not work because first there must be some recode in the extension.

**Comment by fedellen** [comment]
This worked just fine for now; no auto rejection email. I'll update you if anything UnityAds related  comes from Apple review.

Thanks for the fix! I'll close the issue.
